export {default as NavBar} from "../commonComponents/ComponentNavbar/ComponentNavbar"
export {default as Page} from "../components/ComponentPage/ComponentPage"
export {default as Title } from "../commonComponents/ComponentTitle/ComponentTitle"
export {default as Text} from "../components/ComponentText/ComponentText"
export {default as Logo} from "../Assets/svgComponent/Logo"
export {default as  Image} from "../components/ComponentImage/ComponentImage"
export {default as  Button} from "../commonComponents/ComponentButton/ComponentButton"
export {default as  Menu} from "../commonComponents/ComponentMenu/ComponentMenu"
export {default as Search} from "../Assets/svgComponent/Search"